# Generated by Django 4.2.4 on 2023-09-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=50)),
                ('experiance', models.CharField(max_length=20)),
                ('salary', models.BigIntegerField(default='')),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
